# rustfmt stable is not actually usable
# so, format with: cargo +nightly fmt

edition = "2021"
max_width = 120
version = "Two"

binop_separator = "Back"
brace_style = "SameLineWhere"
error_on_line_overflow = true
error_on_unformatted = true
force_explicit_abi = true
imports_granularity = "Crate"
match_block_trailing_comma = true
newline_style = "Unix"
reorder_impl_items = true
reorder_imports = true
trailing_semicolon = false
unstable_features = true
